#!/usr/bin/python3
import sys
from math import sqrt

test_file = open(sys.argv[1], 'r')
nums_arr = [int(x[0:-1]) for x in list(test_file)]

first_num = 2

def is_prime(n):
    flag = 0

    if(n > 1):
        for k in range(2, int(sqrt(n)) + 1):
            if (n % k == 0):
                flag = 1
            break
        if (flag == 0):
            return True
        else:
            return False
    else:
        return False

i = 0
while i < len(nums_arr):
    num = nums_arr[i] / first_num
    if num.is_integer() and is_prime(num):
        print("{}={}*{}".format(nums_arr[i], int(num), first_num))
        i += 1
    else:
        first_num += 1
